import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './header'
import Footer from './footer'
import { Toaster } from 'react-hot-toast'
import AuthProvider from '@/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Titulo',
  description: 'Generated by create next app'
}

export default function AdminLayout ({
  children
}: Readonly<{
  children: React.ReactElement
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className} suppressHydrationWarning={true} >
        <Toaster />
          <AuthProvider>
            <>
            <Header />
            {children}
            <Footer />
            </>
          </AuthProvider>
        </body>
    </html>
  )
}
